# Generated by Django 6.0.6 on 2026-07-10 06:26

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/attributes/')),
            ],
            options={
                'verbose_name': 'Attribute',
                'verbose_name_plural': 'Attributes',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('complete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ign', models.CharField(max_length=50)),
                ('discord_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Bakugan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('price', models.IntegerField(default=0)),
                ('power', models.IntegerField(default=320)),
                ('image', models.ImageField(upload_to='uploads/bakugans/')),
                ('trade_type', models.CharField(choices=[('trading', 'Trading'), ('selling', 'Selling'), ('both', 'Both')], max_length=10)),
                ('is_offered', models.BooleanField(default=False)),
                ('attribute', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tradehub.attribute')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='tradehub.user')),
            ],
            options={
                'verbose_name': 'Bakugan',
                'verbose_name_plural': 'Bakugans',
            },
        ),
        migrations.CreateModel(
            name='OfferItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('giving', 'Giving'), ('asking', 'Asking')], max_length=10)),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradehub.bakugan')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tradehub.offer')),
            ],
            options={
                'verbose_name': 'OfferItem',
                'verbose_name_plural': 'OfferItems',
            },
        ),
        migrations.AddField(
            model_name='offer',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_offers', to='tradehub.user'),
        ),
        migrations.AddField(
            model_name='offer',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_offers', to='tradehub.user'),
        ),
    ]
