# Generated by Django 6.0.6 on 2026-07-10 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradehub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bakugan',
            name='is_offered',
        ),
        migrations.RemoveField(
            model_name='bakugan',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='bakugan',
            name='power',
        ),
        migrations.RemoveField(
            model_name='bakugan',
            name='price',
        ),
        migrations.RemoveField(
            model_name='bakugan',
            name='trade_type',
        ),
        migrations.CreateModel(
            name='OwnedBakugan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('price', models.IntegerField(default=0)),
                ('power', models.IntegerField(default=320)),
                ('image', models.ImageField(upload_to='uploads/bakugans/')),
                ('trade_type', models.CharField(choices=[('trading', 'Trading'), ('selling', 'Selling'), ('both', 'Both')], max_length=10, null=True)),
                ('is_offered', models.BooleanField(default=False)),
                ('attribute', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tradehub.attribute')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='tradehub.user')),
            ],
            options={
                'verbose_name': 'OwnedBakugan',
                'verbose_name_plural': 'OwnedBakugans',
            },
        ),
    ]
