# Generated by Django 6.0.6 on 2026-07-10 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradehub', '0002_remove_bakugan_is_offered_remove_bakugan_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownedbakugan',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='ownedbakugan',
            name='image',
        ),
        migrations.RemoveField(
            model_name='ownedbakugan',
            name='name',
        ),
        migrations.RemoveField(
            model_name='ownedbakugan',
            name='price',
        ),
        migrations.AddField(
            model_name='offer',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ownedbakugan',
            name='bakugan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tradehub.bakugan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ownedbakugan',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='tradehub.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ownedbakugan',
            name='trade_type',
            field=models.CharField(choices=[('trading', 'Trading'), ('selling', 'Selling'), ('both', 'Both')], default='both', max_length=10),
            preserve_default=False,
        ),
    ]
