# Generated by Django 6.0.6 on 2026-07-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradehub', '0003_remove_ownedbakugan_attribute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_secret',
            field=models.CharField(default=111111111111, max_length=32),
            preserve_default=False,
        ),
    ]
