# Generated by Django 6.0.6 on 2026-07-11 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradehub', '0004_user_otp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownedbakugan',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
