# Generated by Django 6.0.6 on 2026-07-11 02:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradehub', '0005_ownedbakugan_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownedbakugan',
            name='price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)]),
        ),
    ]
