# Generated by Django 6.0.6 on 2026-07-11 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradehub', '0006_alter_ownedbakugan_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownedbakugan',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
