# Generated by Django 6.0.6 on 2026-07-12 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradehub', '0007_alter_ownedbakugan_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offeritems',
            name='items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradehub.ownedbakugan'),
        ),
    ]
