# Generated by Django 6.0.6 on 2026-07-12 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradehub', '0008_alter_offeritems_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='total_price',
        ),
        migrations.AddField(
            model_name='offer',
            name='receiver_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offer',
            name='sender_price',
            field=models.IntegerField(default=0),
        ),
    ]
