# Generated by Django 6.0.6 on 2026-07-13 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradehub', '0009_remove_offer_total_price_offer_receiver_price_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OfferItems',
            new_name='OfferItem',
        ),
        migrations.RenameField(
            model_name='offeritem',
            old_name='items',
            new_name='item',
        ),
    ]
