# Generated by Django 6.0.6 on 2026-07-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradehub', '0010_rename_offeritems_offeritem_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='date',
            new_name='date_created',
        ),
        migrations.AddField(
            model_name='offer',
            name='receiver_read',
            field=models.BooleanField(default=False),
        ),
    ]
