# Generated by Django 6.0.6 on 2026-07-13 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradehub', '0011_rename_date_offer_date_created_offer_receiver_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='date_created',
            new_name='date',
        ),
    ]
