# Generated by Django 6.0.6 on 2026-07-17 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradehub', '0012_rename_date_created_offer_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='complete',
        ),
    ]
