# Generated by Django 6.0.6 on 2026-07-17 07:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradehub', '0013_remove_offer_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_discord_name', models.CharField(max_length=50)),
                ('receiver_discord_name', models.CharField(max_length=50)),
                ('sender_price', models.IntegerField(default=0)),
                ('receiver_price', models.IntegerField(default=0)),
                ('sender_bakugans', models.JSONField(default=list)),
                ('receiver_bakugans', models.JSONField(default=list)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
