# Generated by Django 6.0.6 on 2026-07-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradehub', '0014_completedoffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownedbakugan',
            name='trade_type',
            field=models.CharField(choices=[('trading', 'Trading'), ('selling', 'Selling'), ('both', 'Both'), ('neither', 'Neither')], max_length=10),
        ),
    ]
